# Generated by Django 3.2.8 on 2021-11-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('race', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other')], max_length=6)),
                ('type', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('G', 'Give'), ('B', 'Breed')], max_length=6)),
                ('location', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('owner', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
