# Generated by Django 3.2.8 on 2021-11-01 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211101_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other')], max_length=1),
        ),
    ]
