# Generated by Django 3.2.8 on 2021-11-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pet_user_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='user_favourite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userfavourite'),
        ),
    ]
