# Generated by Django 3.2.8 on 2021-11-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pet_user_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user_favourite',
        ),
        migrations.AddField(
            model_name='userfavourite',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='myapp.Pet'),
        ),
    ]
