# Generated by Django 3.2.8 on 2021-12-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
