# Generated by Django 3.2.8 on 2021-11-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211129_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavourite',
            name='favourites',
        ),
        migrations.AlterField(
            model_name='pet',
            name='purpose',
            field=models.CharField(choices=[('Give', 'Give'), ('Breed', 'Breed')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], max_length=6),
        ),
    ]
