# Generated by Django 3.2.8 on 2021-11-01 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pet_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
