# Generated by Django 3.2.8 on 2021-11-29 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postBy',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
