# Generated by Django 3.2.8 on 2021-11-29 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_comment_postby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postby', to=settings.AUTH_USER_MODEL),
        ),
    ]
