# Generated by Django 3.2.8 on 2021-12-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
